/*
 * ABM de Usuarios
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	"bapi/go-mux/src/api"
)

func main() {
	log.Printf("Server started")

	router := api.NewRouter()

	s := &http.Server{
		Addr:    "0.0.0.0:8080",
		Handler: router,
	}

	log.Fatal(s.ListenAndServe())
}
