/*
 * ABM de Usuarios
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api

import (
	"encoding/json"
)

type User struct {
	Username string `json:"username,omitempty"`
	Email    string `json:"email,omitempty"`
}

func creteUser(username, email string) User {
	user := User{
		Email:    email,
		Username: username,
	}

	return user
}

func toJson(usuario *User) string {
	e, _ := json.Marshal(usuario)
	return string(e)
}
